Feature/refactoring
Asspleasure/Mahjong pull request #1
Opened 2022-11-07 20:30 UTC by Asspleasure

Хай

2022-11-09 11:29 UTC, leo-frontend requested changes

2022-11-09 11:29 UTC, leo-frontend commented on src/components/board-game/index.jsx
> +import classnames from "classnames"
Be consistent with quotes. Use either `' '` or `" "`

2022-11-09 11:29 UTC, leo-frontend commented on src/components/board-game/index.jsx
> +import classnames from "classnames"
Use `camelCase` for such names
```suggestion
import classNames from "classnames"
```

2022-11-11 16:00 UTC, Hetuko commented
Did all remarks

2022-11-11 16:51 UTC, merged